apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app-chart.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "spring-boot-app-chart.name" . }}