# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package --file java-app-CICD/spring-boot-app/pom.xml
      
    - name: Run JUnit Tests
      run: mvn test --file java-app-CICD/spring-boot-app/pom.xml
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image:  ${{ secrets.DOCKER_USERNAME }}/java-app-cicd
        tags: ${{ github.sha }}
        registry: docker.io
        dockerfile: java-app-CICD/spring-boot-app/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Deploying the app!
      run: kubectl apply -f java-app-CICD/spring-boot-app-manifests/
    - name: Verifying deployment
      run: kubectl rollout status deployment/spring-boot-app
    - name: Updating deployment
      run: kubectl set image --record deployment.apps/spring-boot-app  spring-boot-app=${{ secrets.DOCKER_USERNAME }}/java-app-cicd:${{ github.sha }}
    - name: Verifying updated deployment
      run: kubectl rollout status deployment/spring-boot-app
      
